### PR TITLE
Added questionnaire mock data

### PR DESCRIPTION
**Pull request by Hsankesara**
Added some questionnaire and Fitbit smartwatch mock data

### CODE REVIEW

**Comment by afolarin** [comment]
A couple of points  
 - we should drop the THINC-IT as that is a 3rd party app so not part of the RADAR-base formal ecosystem.
 - I assume this is a replacement of passive and active streams for the previous sample data? Important that the passive and active data are both aligned so that example workflows that rely on active data providing context for passive data are possible with the sample data

**Comment by Hsankesara** [comment]
Yeah, Agreed, will drop the THINC-IT data. 

> I assume this is a replacement of passive and active streams for the previous sample data? Important that the passive and active data are both aligned so that example workflows that rely on active data providing context for passive data are possible with the sample data

Yeah, so active and passive sample date are between the same time-period (which is a week of data). So it would be easy to test any feature for that week.

**Comment by afolarin** [comment]
I wonder if the dataset is a little big for a mock dataset? ~2.3GB getting
image
might just be github though?
Probably we should aim to trim to ~1GB. Suggest either dropping a few participants or trimming to a particular time window length or similar. Depends if better to have longer time series or more participants.

Also, might need to delete the historical commits from this remote (or they will be retained in the repo size)? :thinking:

**Comment by Hsankesara** [comment]
Good point. I will squash the early commits, so it would all be part of one commit.

**Review by afolarin — APPROVED** [review]
LGTM

**Comment by afolarin** [comment]
closes #2

**Pull request merged**
